#ifndef INC_DEFINES_H_
#define INC_DEFINES_H_

#define GPIO_Output_BUZZER_Pin GPIO_PIN_9
#define GPIO_Output_BUZZER_GPIO_Port GPIOB
#define T_NRST_Pin GPIO_PIN_2
#define T_NRST_GPIO_Port GPIOF
#define TIM2_CH1_ENC_A_Pin GPIO_PIN_0
#define TIM2_CH1_ENC_A_GPIO_Port GPIOA
#define TIM2_CH2_ENC_B_Pin GPIO_PIN_1
#define TIM2_CH2_ENC_B_GPIO_Port GPIOA
#define T_VCP_TX_Pin GPIO_PIN_2
#define T_VCP_TX_GPIO_Port GPIOA
#define T_VCP_RX_Pin GPIO_PIN_3
#define T_VCP_RX_GPIO_Port GPIOA
#define GPIO_Output_AS_0_Pin GPIO_PIN_4
#define GPIO_Output_AS_0_GPIO_Port GPIOA
#define GPIO_Output_AS_1_Pin GPIO_PIN_5
#define GPIO_Output_AS_1_GPIO_Port GPIOA
#define GPIO_Output_AS_2_Pin GPIO_PIN_6
#define GPIO_Output_AS_2_GPIO_Port GPIOA
#define GPIO_Output_AS_3_Pin GPIO_PIN_7
#define GPIO_Output_AS_3_GPIO_Port GPIOA
#define TIM3_CH3_ENC_RED_LED_Pin GPIO_PIN_0
#define TIM3_CH3_ENC_RED_LED_GPIO_Port GPIOB
#define GPIO_EXTI1_FAULT_Pin GPIO_PIN_1
#define GPIO_EXTI1_FAULT_GPIO_Port GPIOB
#define GPIO_EXTI1_FAULT_EXTI_IRQn EXTI0_1_IRQn
#define GPIO_Output__HV_SHDN_Pin GPIO_PIN_2
#define GPIO_Output__HV_SHDN_GPIO_Port GPIOB
#define TIM1_CH1_T_L_SW_0_Pin GPIO_PIN_8
#define TIM1_CH1_T_L_SW_0_GPIO_Port GPIOA
#define TIM1_CH2_T_L_SW_1_Pin GPIO_PIN_9
#define TIM1_CH2_T_L_SW_1_GPIO_Port GPIOA
#define TIM3_CH1_ENC_GRN_LED_Pin GPIO_PIN_6
#define TIM3_CH1_ENC_GRN_LED_GPIO_Port GPIOC
#define TIM1_CH3_T_L_SW_2_Pin GPIO_PIN_10
#define TIM1_CH3_T_L_SW_2_GPIO_Port GPIOA
#define GPIO_Output_AS_4_Pin GPIO_PIN_11
#define GPIO_Output_AS_4_GPIO_Port GPIOA
#define GPIO_Output_AS_5_Pin GPIO_PIN_12
#define GPIO_Output_AS_5_GPIO_Port GPIOA
#define T_JTMS_Pin GPIO_PIN_13
#define T_JTMS_GPIO_Port GPIOA
#define T_JTCK_Pin GPIO_PIN_14
#define T_JTCK_GPIO_Port GPIOA
#define GPIO_EXTI15_SW_Pin GPIO_PIN_15
#define GPIO_EXTI15_SW_GPIO_Port GPIOA
#define GPIO_EXTI15_SW_EXTI_IRQn EXTI4_15_IRQn
#define GPIO_Output_IN_3_0_Pin GPIO_PIN_3
#define GPIO_Output_IN_3_0_GPIO_Port GPIOB
#define GPIO_Output_IN_3_1_Pin GPIO_PIN_4
#define GPIO_Output_IN_3_1_GPIO_Port GPIOB
#define GPIO_Output_BCD1_Pin GPIO_PIN_5
#define GPIO_Output_BCD1_GPIO_Port GPIOB
#define GPIO_Output_BCD2_Pin GPIO_PIN_6
#define GPIO_Output_BCD2_GPIO_Port GPIOB
#define GPIO_Output_BCD3_Pin GPIO_PIN_7
#define GPIO_Output_BCD3_GPIO_Port GPIOB
#define GPIO_Output_BCD0_Pin GPIO_PIN_8
#define GPIO_Output_BCD0_GPIO_Port GPIOB

#define NUM_VALVES 6
#define VALVE_ANODE_OFF_STATE 1
#define VALVE_ANODE_ON_STATE 0
#define NUM_BINARY_DIGITS_IN_BCD 4
#define MULTIPLEXER_TIMER_PERIOD_MINUS_ONE 35000 //with 0 prescaler and clkdivby4 should give 4.096ms overflow; with 2 prescaler and clkdivby4 should give 12.288ms overflow
#define MULTIPLEXER_TIMER_PRESCALER 3 //with 0 prescaler and clkdivby4 should give 4.096ms overflow; with 2 prescaler and clkdivby4 should give 12.288ms overflow
#define DEAD_TIME 2000 //max value is realistically 3000, otherwise time measurements on rotary encoder switch are too long
#define DEAD_TIME_MAX 2000

#define MULTIPLEXER_TIMER_INTERRUPT_PRIORITY 0 //has to be zero otherwise dead time fucks shit up, flickering starts occurring
#define ROTARY_ENCODER_SWITCH_INTERRUPT_PRIORITY 0// if not zero, adjusting dead time tends to extend the depression time for the rotary encoder switch
#define ANTI_CATHODE_POISONING_TIMER_INTERRUPT_PRIORITY 2
#define VALVE_BLINK_TIMER_INTERRUPT_PRIORITY 2
#define UART_INTERRUPT_PRIORITY 2

#define ANTI_CATHODE_POISONING_TIMER_WAITING_MODE_PRESCALER 65535  //with clkdivby4 should give ~4.5min overflow
#define ANTI_CATHODE_POISONING_TIMER_WAITING_MODE_PERIOD_MINUS_ONE 65535 //5000(test) //with clkdivby4 should give ~4.5min overflow
#define ANTI_CATHODE_POISONING_TIMER_ACTIVE_MODE_PRESCALER 25 //with clkdivby4 should give 204.8ms overflow //was 49
#define ANTI_CATHODE_POISONING_TIMER_ACTIVE_MODE_PERIOD_MINUS_ONE 65535 //with clkdivby4 should give 204.8ms overflow
#define ANTI_CATHODE_POISONING_MAX_COUNTER 9
#define ANTI_CATHODE_POISONING_MAX_CYCLES 3
#define TIME_ADJUST_BLINK_PERIOD_MINUS_ONE 65535
#define TIME_ADJUST_BLINK_PRESCALER 375
#define TIME_FLASH_BASE_ADDRESS 0x0800F800
#define LPTIM1_CCR_CHECK 250
#define ROTARY_ENCODER_SWITCH_CONFIDENCE_COUNT 14
#define COUNT_TO_DELAY_RISING_ROTARY_ENCODER_EDGE 4

#define ROTARY_ENCODER_MS_DELAY_COUNT_BETWEEN_CHECKS 10
#define NUM_ROTARY_ENCODER_LEDs 2
#define ROTARY_ENCODER_SWITCH_ENTER_SLASH_ADVANCE_TIME_ADJUST_MODE_COUNT_MIN 2000
#define ROTARY_ENCODER_SWITCH_ENTER_SLASH_ADVANCE_TIME_ADJUST_MODE_COUNT_MAX ROTARY_ENCODER_SWITCH_ENTER_SLASH_ADVANCE_TIME_ADJUST_MODE_COUNT_MIN + 2000
#define ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MIN 5250
#define ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MAX ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MIN + 2250
#define SET_ALARM_ADVANCE_COUNT_MIN ROTARY_ENCODER_SWITCH_ENTER_SLASH_ADVANCE_TIME_ADJUST_MODE_COUNT_MIN
#define SET_ALARM_ADVANCE_COUNT_MAX ROTARY_ENCODER_SWITCH_ENTER_SLASH_ADVANCE_TIME_ADJUST_MODE_COUNT_MAX
#define SET_ALARM_COUNT_MIN ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MIN
#define SET_ALARM_COUNT_MAX ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MAX
#define SET_ALARM_SAVE_COUNT_MIN ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MIN
#define SET_ALARM_SAVE_COUNT_MAX ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MAX
#define CLEAR_ALARM_COUNT_MIN 50
#define CLEAR_ALARM_COUNT_MAX 500
#define CANCEL_ALARM_COUNT_MIN ROTARY_ENCODER_SWITCH_SAVE_TIME_COUNT_MAX + 750
#define CANCEL_ALARM_COUNT_MAX CANCEL_ALARM_COUNT_MIN + 2750
#define BUZZER_SHORT_TONE_COUNT 20000
#define BUZZER_SHORT_OFF_COUNT 20000
#define BUZZER_LONG_OFF_COUNT 40000
#define BUZZER_COUNT_MAX BUZZER_SHORT_TONE_COUNT + BUZZER_SHORT_TONE_COUNT + BUZZER_SHORT_OFF_COUNT + BUZZER_LONG_OFF_COUNT
#define ADJUST_TIME_GREEN_LED_BRIGHTNESS_CCR 10000
#define ALARM_SET_GREEN_LED_BRIGHTNESS_CCR 5000
#define ALARM_SET_RED_LED_BRIGHTNESS_CCR 20000
#define FAULT_RED_LED_BRIGHTNESS_CCR 65535
#define ROTARY_ENCODER_RED_LED_NUM 1
#define ROTARY_ENCODER_GREEN_LED_NUM 0
#define LED_SHORT_ON_COUNT 16
#define LED_SHORT_OFF_COUNT 32
#define LED_DOUBLE_FLASH_COUNT_MAX (LED_SHORT_ON_COUNT << 1) + (LED_SHORT_OFF_COUNT << 1)
#define RED_LED_DOUBLE_FLASH_BRIGHTNESS_CCR 30000

#define CALP_DECREASE_FREQUENCY 0
#define CALP_INCREASE_FREQUENCY 1
#define CALM_DEFAULT 260

#define CHANGE_DEAD_TIME_COMMAND 0x00
#define CHANGE_CALM_COMMAND 0x01
#define CALM_MAX 511
#define CHANGE_CALP_COMMAND 0x02
#define COMMAND_PLUS_ARGUMENT_NUM_BYTES 2
#define COMMAND_INDEX 0
#define VALUE_INDEX 1
#define RESPONSE_NUM_BYTES 1
#define RESPONSE_INDEX 0

#define TRI_WAVETABLE_SIZE 256

#endif /* INC_DEFINES_H_ */
